
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 23 12:18:22 CST 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENDER = 7;
  public static final int PARENIZQ = 6;
  public static final int error = 1;
  public static final int EXPONENTE = 5;
  public static final int FLOTANTE = 3;
  public static final int OPERADOR = 4;
  public static final int EOF = 0;
  public static final int ENTERO = 2;
}

